### ISSUE TITLE
waterline initialize failed, err: { userError: Could not find a primary key attribute on the model `acl_user`. All models must contain an attribute that acts as the primary key and is guaranteed to be unique.

### ISSUE THREAD

**Issue by zhangtanlin** [wuwanyu/aclDemo#4]
我准备把你这个拆成前后端分离的项目（在用express脚手架构建的基础上），在修改了app和config以及bin/www文件后，报了个这个错你能够解决一下？
方便留个联系方式？我打算用这个做管理系统的基础，想和你深度交流下。

waterline initialize failed, err: { userError: Could not find a primary key attribute on the model `acl_user`. All models must contain an attribute that acts as the primary key and is guaranteed to be unique.
    at normalizeCollection (E:\obj\monitor\node_modules\waterline-schema\lib\waterline-schema\schema.js:85:44)
    at arrayEach (E:\obj\monitor\node_modules\@sailshq\lodash\lib\index.js:1463:13)
    at Function.<anonymous> (E:\obj\monitor\node_modules\@sailshq\lodash\lib\index.js:3525:13)
    at schemaBuilder (E:\obj\monitor\node_modules\waterline-schema\lib\waterline-schema\schema.js:34:5)
    at new WaterlineSchema (E:\obj\monitor\node_modules\waterline-schema\lib\waterline-schema.js:36:12)
    at Object.initialize (E:\obj\monitor\node_modules\waterline\lib\waterline.js:581:26)
    at Object.<anonymous> (E:\obj\monitor\bin\www:14:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3 name: 'userError' }

**Comment by wuwanyu** [comment]
抱歉最近比较忙刚看到，我的邮箱是wuwanyu_321@163.com，希望能与你多交流。
根据报错，感觉是acl_user缺少主键，或者你可以打包发给我，我帮你调试一下

**Comment by zhangtanlin** [comment]
大概解决了，是model的问题
